### ISSUE TITLE
ArrayList goes empty after restarting app

### ISSUE THREAD

**Issue by nightfury96** [MarcinMoskala/PreferenceHolder#8]
Hi,
i use below line to add product (data class) to cart in sharedpreference:
var CartItems: ArrayList<ResDataClass.Companion.Product> by bindToPreferenceField(arrayListOf())
when app is alive CartItems has values
but after restarting app CartItems goes Empty
everything except arraylist in sharedpreference has value
something's wrong in saving arrays in sharedpreference
plz fix it
thanks

**Comment by yguel** [comment]
Hi,
I have the same issue here for any Mutable collection so far and and any collection stored inside an object.
Is this the expected behaviour ?

**Comment by NunciosChums** [comment]
I have same issue and I think same with #2 
https://youtu.be/l1I0jeNaVkw

I'm using 
```
var readNoticeIds: HashSet<Int> by bindToPreferenceField(hashSetOf())
```

**Comment by xeropresence** [comment]
Yes, it seems that there is an issue with collections.

If you declare

```
var readNoticeIds: HashSet<Int> by bindToPreferenceField(hashSetOf())
```
then do

```
val localCopy = readNoticeIds
readNoticeIds.add(5)
readNoticeIds = hashSetOf()
readNoticeIds = localCopy
```

It will save, so simply modifying the collection seems to be insufficient to trigger a save

**Comment by MarcinMoskala** [comment]
This is expected behavior as mutable object change does not modify preferences. Use immutable objects. The same problem references all collections that have some persistence or internal structure depending on their state. 
```
data class FullName(
   var name: String,
   var surname: String
)

val person = FullName("Maja", "Markiewicz")
val set = mutableSetOf<FullName>()
set.add(person)
person.surname = "Moskała"
print(person) // FullName(name=Maja, surname=Moskała)
print(person in set) // false
print(set) // [FullName(name=Maja, surname=Moskała)]
```
