### ISSUE TITLE
object changes not saved

### ISSUE THREAD

**Issue by duz17** [MarcinMoskala/PreferenceHolder#9]
I use this library to save any type of object
in PreferenceFieldBinder you got this line of code:
    override fun setValue(thisRef: PreferenceHolder, property: KProperty<*>, value: T) {
        if (value == field) return

meaning that if I change object and try to save it again it not saved

**Comment by joseAugustoCR** [comment]
I have the same problem.

As a workaround, I set the object to null before applying the new value

**Comment by yooneskh** [comment]
i had this problem too and @joseAugustoCR workaround worked for me.
